In [34]:
import numpy as np
arr=np.array([[1,2,3,4,5],[5,4,3,2,1]])
print (arr)

[[1 2 3 4 5]
 [5 4 3 2 1]]


In [14]:
x=((1,2,3,4,5),(5,4,3,2,1))
np_x=np.array(x)
np_x

array([[1, 2, 3, 4, 5],
       [5, 4, 3, 2, 1]])

In [19]:
np_x.ndim

2

In [3]:
arr=np.array([[1,2,3,4],[5,6,7,8],[3,4,5,6]])
print(arr.ndim)
print(arr.shape)

2
(3, 4)


In [4]:
arr=np.array([10,20,30,40])
newarr=arr.reshape(1,4)
print(newarr)

[[10 20 30 40]]


In [12]:
arr=np.array([10,20,30,40,50,60,70,80,90,100])
newarr=arr.reshape(-1,5)
print (newarr)

[[ 10  20  30  40  50]
 [ 60  70  80  90 100]]


In [35]:
arr=np.array([[1,2,3],[5,6,7],[9,10,11],[4,8,12]])
arr2=np.copy(arr)
print(arr2)
arr2.shape

[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [ 4  8 12]]


(4, 3)

In [36]:
for i in range(0,4):
    for j in range(0,3):
        arr2[i][j]*=2
print(arr2)


[[ 2  4  6]
 [10 12 14]
 [18 20 22]
 [ 8 16 24]]


In [43]:
arr=arr.flatten()
print(arr)

[ 1  2  3  5  6  7  9 10 11  4  8 12]


In [39]:
arr2=arr2.reshape(2,-1)
print (arr2)

[[ 2  4  6 10 12 14]
 [18 20 22  8 16 24]]
